# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emotalk_pb2 as emotalk__pb2


class EmoTalkServiceStub(object):
    """Service định nghĩa cho EmoTalk API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAudio = channel.unary_stream(
                '/emotalk.EmoTalkService/ProcessAudio',
                request_serializer=emotalk__pb2.AudioRequest.SerializeToString,
                response_deserializer=emotalk__pb2.BlendshapeResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/emotalk.EmoTalkService/HealthCheck',
                request_serializer=emotalk__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=emotalk__pb2.HealthCheckResponse.FromString,
                )


class EmoTalkServiceServicer(object):
    """Service định nghĩa cho EmoTalk API
    """

    def ProcessAudio(self, request, context):
        """Stream blendshapes từ audio input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmoTalkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessAudio,
                    request_deserializer=emotalk__pb2.AudioRequest.FromString,
                    response_serializer=emotalk__pb2.BlendshapeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=emotalk__pb2.HealthCheckRequest.FromString,
                    response_serializer=emotalk__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotalk.EmoTalkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmoTalkService(object):
    """Service định nghĩa cho EmoTalk API
    """

    @staticmethod
    def ProcessAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/emotalk.EmoTalkService/ProcessAudio',
            emotalk__pb2.AudioRequest.SerializeToString,
            emotalk__pb2.BlendshapeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emotalk.EmoTalkService/HealthCheck',
            emotalk__pb2.HealthCheckRequest.SerializeToString,
            emotalk__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
