# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emotalk.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\remotalk.proto\x12\x07\x65motalk\"\xa8\x01\n\x0c\x41udioRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x15\n\remotion_level\x18\x03 \x01(\x05\x12\x11\n\tperson_id\x18\x04 \x01(\x05\x12\x17\n\x0fpost_processing\x18\x05 \x01(\x08\x12\x16\n\x0e\x63hunk_duration\x18\x06 \x01(\x02\x12\x15\n\rchunk_overlap\x18\x07 \x01(\x02\"\x90\x01\n\x12\x42lendshapeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12(\n\x06\x66rames\x18\x03 \x03(\x0b\x32\x18.emotalk.BlendshapeFrame\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\"N\n\x0f\x42lendshapeFrame\x12\x10\n\x08timecode\x18\x01 \x01(\x01\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x05\x12\x13\n\x0b\x62lendshapes\x18\x03 \x03(\x02\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x8d\x01\n\x13HealthCheckResponse\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.emotalk.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xa0\x01\n\x0e\x45moTalkService\x12\x44\n\x0cProcessAudio\x12\x15.emotalk.AudioRequest\x1a\x1b.emotalk.BlendshapeResponse0\x01\x12H\n\x0bHealthCheck\x12\x1b.emotalk.HealthCheckRequest\x1a\x1c.emotalk.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotalk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=27
  _globals['_AUDIOREQUEST']._serialized_end=195
  _globals['_BLENDSHAPERESPONSE']._serialized_start=198
  _globals['_BLENDSHAPERESPONSE']._serialized_end=342
  _globals['_BLENDSHAPEFRAME']._serialized_start=344
  _globals['_BLENDSHAPEFRAME']._serialized_end=422
  _globals['_HEALTHCHECKREQUEST']._serialized_start=424
  _globals['_HEALTHCHECKREQUEST']._serialized_end=461
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=464
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=605
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=547
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=605
  _globals['_EMOTALKSERVICE']._serialized_start=608
  _globals['_EMOTALKSERVICE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
