# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import emotalk_pb2 as emotalk__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in emotalk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmoTalkServiceStub(object):
    """Service định nghĩa cho EmoTalk API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAudio = channel.unary_stream(
                '/emotalk.EmoTalkService/ProcessAudio',
                request_serializer=emotalk__pb2.AudioRequest.SerializeToString,
                response_deserializer=emotalk__pb2.BlendshapeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/emotalk.EmoTalkService/HealthCheck',
                request_serializer=emotalk__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=emotalk__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class EmoTalkServiceServicer(object):
    """Service định nghĩa cho EmoTalk API
    """

    def ProcessAudio(self, request, context):
        """Stream blendshapes từ audio input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmoTalkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessAudio,
                    request_deserializer=emotalk__pb2.AudioRequest.FromString,
                    response_serializer=emotalk__pb2.BlendshapeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=emotalk__pb2.HealthCheckRequest.FromString,
                    response_serializer=emotalk__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotalk.EmoTalkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emotalk.EmoTalkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmoTalkService(object):
    """Service định nghĩa cho EmoTalk API
    """

    @staticmethod
    def ProcessAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emotalk.EmoTalkService/ProcessAudio',
            emotalk__pb2.AudioRequest.SerializeToString,
            emotalk__pb2.BlendshapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotalk.EmoTalkService/HealthCheck',
            emotalk__pb2.HealthCheckRequest.SerializeToString,
            emotalk__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
